name: Build and Upload

on: 
  push:
    branches:
      - master

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Upload 🚀
        uses: s0/git-publish-subdir-action@develop
        with:
          branch: build
          folder: dist
          env:
            REPO: self
            BRANCH: build
            FOLDER: build
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
